// <auto-generated />
using System;
using FamilyRelocation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyRelocation.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260120182542_AddConfigurableDocumentSystem")]
    partial class AddConfigurableDocumentSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.Applicant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ApplicantId");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentKehila")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShabbosShul")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Applicants", (string)null);
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.ApplicantDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("ApplicantId", "DocumentTypeId");

                    b.ToTable("ApplicantDocuments", (string)null);
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.DocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DocumentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Agreement to work with the community's broker",
                            DisplayName = "Broker Agreement",
                            IsActive = true,
                            IsSystemType = true,
                            Name = "BrokerAgreement"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb02"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Community guidelines and rules agreement",
                            DisplayName = "Community Takanos",
                            IsActive = true,
                            IsSystemType = true,
                            Name = "CommunityTakanos"
                        });
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.HousingSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("HousingSearchId");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MovedInDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MovedInStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StageChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId")
                        .IsUnique();

                    b.HasIndex("CreatedDate");

                    b.HasIndex("IsActive");

                    b.HasIndex("Stage");

                    b.ToTable("HousingSearches", (string)null);
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.StageTransitionRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStage")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ToStage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("FromStage", "ToStage");

                    b.HasIndex("FromStage", "ToStage", "DocumentTypeId")
                        .IsUnique();

                    b.ToTable("StageTransitionRequirements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc01"),
                            DocumentTypeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01"),
                            FromStage = 1,
                            IsRequired = true,
                            ToStage = 3
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccc02"),
                            DocumentTypeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb02"),
                            FromStage = 1,
                            IsRequired = true,
                            ToStage = 3
                        });
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.Applicant", b =>
                {
                    b.OwnsOne("FamilyRelocation.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address_Street");

                            b1.Property<string>("Street2")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address_Street2");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("Address_ZipCode");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.OwnsOne("FamilyRelocation.Domain.ValueObjects.BoardReview", "BoardReview", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Decision")
                                .HasColumnType("integer")
                                .HasColumnName("BoardDecision");

                            b1.Property<string>("Notes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("BoardDecisionNotes");

                            b1.Property<DateTime>("ReviewDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("BoardReviewDate");

                            b1.Property<Guid>("ReviewedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("BoardReviewedByUserId");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.OwnsMany("FamilyRelocation.Domain.ValueObjects.Child", "Children", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Age");

                            b1.Property<int>("Gender");

                            b1.Property<string>("Name");

                            b1.Property<string>("School");

                            b1.HasKey("ApplicantId", "__synthesizedOrdinal");

                            b1.ToTable("Applicants");

                            b1
                                .ToJson("Children")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");
                        });

                    b.OwnsOne("FamilyRelocation.Domain.ValueObjects.HusbandInfo", "Husband", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId");

                            b1.Property<string>("Email");

                            b1.Property<string>("EmployerName");

                            b1.Property<string>("FatherName");

                            b1.Property<string>("FirstName")
                                .IsRequired();

                            b1.Property<string>("LastName")
                                .IsRequired();

                            b1.Property<string>("Occupation");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1
                                .ToJson("Husband")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");

                            b1.OwnsMany("FamilyRelocation.Domain.ValueObjects.PhoneNumber", "PhoneNumbers", b2 =>
                                {
                                    b2.Property<Guid>("HusbandInfoApplicantId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<bool>("IsPrimary");

                                    b2.Property<string>("Number")
                                        .IsRequired();

                                    b2.Property<int>("Type");

                                    b2.HasKey("HusbandInfoApplicantId", "__synthesizedOrdinal");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("HusbandInfoApplicantId");
                                });

                            b1.Navigation("PhoneNumbers");
                        });

                    b.OwnsOne("FamilyRelocation.Domain.ValueObjects.SpouseInfo", "Wife", b1 =>
                        {
                            b1.Property<Guid>("ApplicantId");

                            b1.Property<string>("Email");

                            b1.Property<string>("EmployerName");

                            b1.Property<string>("FatherName");

                            b1.Property<string>("FirstName")
                                .IsRequired();

                            b1.Property<string>("HighSchool");

                            b1.Property<string>("MaidenName");

                            b1.Property<string>("Occupation");

                            b1.HasKey("ApplicantId");

                            b1.ToTable("Applicants");

                            b1
                                .ToJson("Wife")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ApplicantId");

                            b1.OwnsMany("FamilyRelocation.Domain.ValueObjects.PhoneNumber", "PhoneNumbers", b2 =>
                                {
                                    b2.Property<Guid>("SpouseInfoApplicantId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<bool>("IsPrimary");

                                    b2.Property<string>("Number")
                                        .IsRequired();

                                    b2.Property<int>("Type");

                                    b2.HasKey("SpouseInfoApplicantId", "__synthesizedOrdinal");

                                    b2.ToTable("Applicants");

                                    b2.WithOwner()
                                        .HasForeignKey("SpouseInfoApplicantId");
                                });

                            b1.Navigation("PhoneNumbers");
                        });

                    b.Navigation("Address");

                    b.Navigation("BoardReview");

                    b.Navigation("Children");

                    b.Navigation("Husband")
                        .IsRequired();

                    b.Navigation("Wife");
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.ApplicantDocument", b =>
                {
                    b.HasOne("FamilyRelocation.Domain.Entities.Applicant", "Applicant")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyRelocation.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.HousingSearch", b =>
                {
                    b.HasOne("FamilyRelocation.Domain.Entities.Applicant", "Applicant")
                        .WithOne("HousingSearch")
                        .HasForeignKey("FamilyRelocation.Domain.Entities.HousingSearch", "ApplicantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FamilyRelocation.Domain.ValueObjects.Contract", "CurrentContract", b1 =>
                        {
                            b1.Property<Guid>("HousingSearchId");

                            b1.Property<DateTime?>("ActualClosingDate");

                            b1.Property<DateTime>("ContractDate");

                            b1.Property<DateTime?>("ExpectedClosingDate");

                            b1.Property<Guid>("PropertyId");

                            b1.HasKey("HousingSearchId");

                            b1.ToTable("HousingSearches");

                            b1
                                .ToJson("CurrentContract")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HousingSearchId");

                            b1.OwnsOne("FamilyRelocation.Domain.ValueObjects.Money", "Price", b2 =>
                                {
                                    b2.Property<Guid>("ContractHousingSearchId");

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();

                                    b2.HasKey("ContractHousingSearchId");

                                    b2.ToTable("HousingSearches");

                                    b2.WithOwner()
                                        .HasForeignKey("ContractHousingSearchId");
                                });

                            b1.Navigation("Price")
                                .IsRequired();
                        });

                    b.OwnsMany("FamilyRelocation.Domain.ValueObjects.FailedContractAttempt", "_failedContracts", b1 =>
                        {
                            b1.Property<Guid>("HousingSearchId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<DateTime>("FailedDate");

                            b1.Property<string>("Reason");

                            b1.HasKey("HousingSearchId", "__synthesizedOrdinal");

                            b1.ToTable("HousingSearches");

                            b1
                                .ToJson("FailedContracts")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HousingSearchId");

                            b1.OwnsOne("FamilyRelocation.Domain.ValueObjects.Contract", "Contract", b2 =>
                                {
                                    b2.Property<Guid>("FailedContractAttemptHousingSearchId");

                                    b2.Property<int>("FailedContractAttempt__synthesizedOrdinal");

                                    b2.Property<DateTime?>("ActualClosingDate");

                                    b2.Property<DateTime>("ContractDate");

                                    b2.Property<DateTime?>("ExpectedClosingDate");

                                    b2.Property<Guid>("PropertyId");

                                    b2.HasKey("FailedContractAttemptHousingSearchId", "FailedContractAttempt__synthesizedOrdinal");

                                    b2.ToTable("HousingSearches");

                                    b2.WithOwner()
                                        .HasForeignKey("FailedContractAttemptHousingSearchId", "FailedContractAttempt__synthesizedOrdinal");

                                    b2.OwnsOne("FamilyRelocation.Domain.ValueObjects.Money", "Price", b3 =>
                                        {
                                            b3.Property<Guid>("ContractFailedContractAttemptHousingSearchId");

                                            b3.Property<int>("ContractFailedContractAttempt__synthesizedOrdinal");

                                            b3.Property<decimal>("Amount");

                                            b3.Property<string>("Currency")
                                                .IsRequired();

                                            b3.HasKey("ContractFailedContractAttemptHousingSearchId", "ContractFailedContractAttempt__synthesizedOrdinal");

                                            b3.ToTable("HousingSearches");

                                            b3.WithOwner()
                                                .HasForeignKey("ContractFailedContractAttemptHousingSearchId", "ContractFailedContractAttempt__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Price")
                                        .IsRequired();
                                });

                            b1.Navigation("Contract")
                                .IsRequired();
                        });

                    b.OwnsOne("FamilyRelocation.Domain.ValueObjects.HousingPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("HousingSearchId");

                            b1.Property<decimal?>("MinBathrooms");

                            b1.Property<int?>("MinBedrooms");

                            b1.Property<int?>("MoveTimeline");

                            b1.PrimitiveCollection<string>("RequiredFeatures")
                                .IsRequired();

                            b1.HasKey("HousingSearchId");

                            b1.ToTable("HousingSearches");

                            b1
                                .ToJson("Preferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HousingSearchId");

                            b1.OwnsOne("FamilyRelocation.Domain.ValueObjects.Money", "Budget", b2 =>
                                {
                                    b2.Property<Guid>("HousingPreferencesHousingSearchId");

                                    b2.Property<decimal>("Amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired();

                                    b2.HasKey("HousingPreferencesHousingSearchId");

                                    b2.ToTable("HousingSearches");

                                    b2.WithOwner()
                                        .HasForeignKey("HousingPreferencesHousingSearchId");
                                });

                            b1.OwnsOne("FamilyRelocation.Domain.ValueObjects.ShulProximityPreference", "ShulProximity", b2 =>
                                {
                                    b2.Property<Guid>("HousingPreferencesHousingSearchId");

                                    b2.Property<bool>("AnyShulAcceptable");

                                    b2.Property<double?>("MaxWalkingDistanceMiles");

                                    b2.Property<int?>("MaxWalkingTimeMinutes");

                                    b2.PrimitiveCollection<string>("PreferredShulIds")
                                        .IsRequired();

                                    b2.HasKey("HousingPreferencesHousingSearchId");

                                    b2.ToTable("HousingSearches");

                                    b2.WithOwner()
                                        .HasForeignKey("HousingPreferencesHousingSearchId");
                                });

                            b1.Navigation("Budget");

                            b1.Navigation("ShulProximity");
                        });

                    b.Navigation("Applicant");

                    b.Navigation("CurrentContract");

                    b.Navigation("Preferences");

                    b.Navigation("_failedContracts");
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.StageTransitionRequirement", b =>
                {
                    b.HasOne("FamilyRelocation.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("FamilyRelocation.Domain.Entities.Applicant", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("HousingSearch");
                });
#pragma warning restore 612, 618
        }
    }
}
