namespace FamilyRelocation.Domain.Common;

/// <summary>
/// Well-known GUIDs used throughout the system.
/// These use patterns that cannot be generated by UUID v4 (Guid.NewGuid()),
/// ensuring no collision with system-generated IDs.
/// </summary>
public static class WellKnownIds
{
    /// <summary>
    /// Used when an applicant submits their own application (anonymous/public submission).
    /// Pattern: All A's - structurally invalid as UUID v4, guaranteed unique.
    /// </summary>
    public static readonly Guid SelfSubmittedUserId = new("AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA");
}
